//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensational_Scents_F
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sensational_ScentsEntities : DbContext
    {
        public Sensational_ScentsEntities()
            : base("name=Sensational_ScentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SensationalRecord> SensationalRecords { get; set; }
        public virtual DbSet<TypesofProductsUpdated> TypesofProductsUpdateds { get; set; }
    }
}
